# Generated by Django 3.0.8 on 2020-08-25 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='education',
            new_name='education_model',
        ),
    ]
