# Generated by Django 3.0.8 on 2020-08-27 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contactmessages'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contactmessages',
            table=None,
        ),
    ]
