# Generated by Django 3.0.8 on 2020-08-29 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200829_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprojects',
            name='image',
            field=models.ImageField(default='none', upload_to='images/'),
            preserve_default=False,
        ),
    ]
