# Generated by Django 3.0.8 on 2020-09-01 03:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200831_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecomment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.time(8, 56, 27, 386653)),
        ),
    ]
