# Generated by Django 3.0.8 on 2020-09-01 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_articlecomment_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecomment',
            name='comment_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
