# Generated by Django 3.0.8 on 2020-09-01 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200901_0857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlecomment',
            name='comment_date',
        ),
    ]
