# Generated by Django 3.0.8 on 2020-09-01 03:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_articlecomment_comment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecomment',
            name='comment_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
