# Generated by Django 3.0.8 on 2020-09-01 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_articlecomment_comment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlecomment',
            name='comment_date',
        ),
    ]
